scripts:
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android --no-install
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease
